fix(test.yml): fix incorrect step order in workflow file to ensure correct execution order feat(test.yml): add test for liquibase version to verify correct installation and setup

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -36,23 +36,6 @@ jobs:
         run: |
           docker build -f ${{ matrix.dockerfile }} -t liquibase/liquibase:${{ github.sha }} .
 
-      - name: Test liquibase version
-        run: |
-          LOG_STRING="Liquibase Version:"
-          # Check if the container is running
-          if docker inspect -f '{{.State.Running}}' "$CONTAINER_NAME" 2>/dev/null | grep -q "true"; then
-              # Get the logs and check if the desired string is present
-              if docker exec $CONTAINER_NAME liquibase --version 2>&1 | grep -q "$LOG_STRING"; then
-                  echo "The log contains the string: $LOG_STRING"
-              else
-                  echo "The log does not contain the string: $LOG_STRING"
-                  exit 1
-              fi
-          else
-              echo "Error: Container $CONTAINER_NAME is not running."
-              exit 2
-          fi
-
       - name: Test liquibase init start-h2
         run: |
           docker run --name $CONTAINER_NAME -d -v $(pwd)/.github/test:/liquibase/changelog liquibase/liquibase:${{ github.sha }} init start-h2
@@ -63,6 +46,23 @@ jobs:
           if docker inspect -f '{{.State.Running}}' "$CONTAINER_NAME" 2>/dev/null | grep -q "true"; then
               # Get the logs and check if the desired string is present
               if docker logs "$CONTAINER_NAME" 2>&1 | grep -q "$LOG_STRING"; then
+                  echo "The log contains the string: $LOG_STRING"
+              else
+                  echo "The log does not contain the string: $LOG_STRING"
+                  exit 1
+              fi
+          else
+              echo "Error: Container $CONTAINER_NAME is not running."
+              exit 2
+          fi
+
+      - name: Test liquibase version
+        run: |
+          LOG_STRING="Liquibase Version:"
+          # Check if the container is running
+          if docker inspect -f '{{.State.Running}}' "$CONTAINER_NAME" 2>/dev/null | grep -q "true"; then
+              # Get the logs and check if the desired string is present
+              if docker exec $CONTAINER_NAME liquibase --version 2>&1 | grep -q "$LOG_STRING"; then
                   echo "The log contains the string: $LOG_STRING"
               else
                   echo "The log does not contain the string: $LOG_STRING"
