chore: add .DS_Store files to .gitignore
feat(test.yml): add test for extension loading in the GitHub Actions workflow

The .DS_Store files are binary files generated by macOS that are not necessary for version control. Adding them to the .gitignore file will prevent them from being tracked.

In the test.yml file, a new step is added to test the loading of an extension in the GitHub Actions workflow. It starts a Docker container, runs a Liquibase command, and checks if the desired log string is present. This test ensures that the extension loading functionality is working correctly.

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -150,3 +150,26 @@ jobs:
               echo "Error: Container $CONTAINER_NAME is not running."
               exit 2
           fi
+
+      - name: Test extension loading
+        run: |
+          LOG_STRING="Update has been successful"
+          # Stop docker container
+          docker stop $CONTAINER_NAME
+          # Start docker container
+          docker run --name $CONTAINER_NAME -d -v $(pwd)/.github/test:/liquibase/changelog -v $(pwd)/.github/test/extensions:/liquibase/classpath liquibase/liquibase:${{ github.sha }} init start-h2
+          sleep 5
+          docker logs $CONTAINER_NAME
+          # Check if the container is running
+          if docker inspect -f '{{.State.Running}}' "$CONTAINER_NAME" 2>/dev/null | grep -q "true"; then
+              # Get the logs and check if the desired string is present
+              if docker logs "$CONTAINER_NAME" 2>&1 | grep -q "$LOG_STRING"; then
+                  echo "The log contains the string: $LOG_STRING"
+              else
+                  echo "The log does not contain the string: $LOG_STRING"
+                  exit 1
+              fi
+          else
+              echo "Error: Container $CONTAINER_NAME is not running."
+              exit 2
+          fi
