test(test.yml): add volume persistence test to ensure that the desired log string is present after restarting the container
The volume persistence test checks if the desired log string "Update has been successful" is present after stopping and starting the Docker container.

The test performs the following steps:
1. Sets the `LOG_STRING` variable to "Update has been successful"
2. Stops the Docker container specified by the `CONTAINER_NAME` variable
3. Starts the Docker container specified by the `CONTAINER_NAME` variable
4. Waits for 5 seconds to allow the container to start
5. Checks if the container is running
6. If the container is running, it executes the `liquibase update` command inside the container and redirects the output to check if the log string is present
7. If the log string is present, it prints "The log contains the string: $LOG_STRING"
8. If the log string is not present, it prints "The log does not contain the string: $LOG_STRING" and exits with code 1
9. If the container is not running, it prints "Error: Container $CONTAINER_NAME is not running." and exits with code 2

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -128,3 +128,25 @@ jobs:
               echo "Error: Container $CONTAINER_NAME is not running."
               exit 2
           fi
+
+      - name: Test volume persistence
+        run: |
+          LOG_STRING="Update has been successful"
+          # Stop docker container
+          docker stop $CONTAINER_NAME
+          # Start docker container
+          docker start $CONTAINER_NAME
+          sleep 5
+          # Check if the container is running
+          if docker inspect -f '{{.State.Running}}' "$CONTAINER_NAME" 2>/dev/null | grep -q "true"; then
+              # Get the logs and check if the desired string is present
+              if docker exec $CONTAINER_NAME liquibase update --defaultsFile=/liquibase/changelog/liquibase.properties --changelog-file=/changelog/example-changelog.xml 2>&1 | grep -q "$LOG_STRING"; then
+                  echo "The log contains the string: $LOG_STRING"
+              else
+                  echo "The log does not contain the string: $LOG_STRING"
+                  exit 1
+              fi
+          else
+              echo "Error: Container $CONTAINER_NAME is not running."
+              exit 2
+          fi
