chore(test.yml): add CONTAINER_NAME environment variable to improve readability and reusability fix(test.yml): update test step to check if the container is running and if the desired log string is present

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -17,6 +17,8 @@ permissions:
 
 jobs:
   test:
+    env:
+      CONTAINER_NAME: "liquibase"
     strategy:
       fail-fast: false
       matrix:
@@ -38,7 +40,6 @@ jobs:
           docker run --name liquibase -d -v $(pwd)/.github/test:/liquibase/changelog liquibase/liquibase:${{ github.sha }} init start-h2
           sleep 5
           docker logs liquibase
-          CONTAINER_NAME="liquibase"
           LOG_STRING="jdbc:h2:tcp://localhost:9090/mem:dev"
           # Check if the container is running
           if docker inspect -f '{{.State.Running}}' "$CONTAINER_NAME" 2>/dev/null | grep -q "true"; then
@@ -58,6 +59,20 @@ jobs:
         run: |
           docker exec liquibase liquibase --version
           docker logs liquibase
+          LOG_STRING="Liquibase Version:"
+          # Check if the container is running
+          if docker inspect -f '{{.State.Running}}' "$CONTAINER_NAME" 2>/dev/null | grep -q "true"; then
+              # Get the logs and check if the desired string is present
+              if docker logs "$CONTAINER_NAME" 2>&1 | grep -q "$LOG_STRING"; then
+                  echo "The log contains the string: $LOG_STRING"
+              else
+                  echo "The log does not contain the string: $LOG_STRING"
+                  exit 1
+              fi
+          else
+              echo "Error: Container $CONTAINER_NAME is not running."
+              exit 2
+          fi
 
       - name: Run Liquibase update
         run: |
