fix(test.yml): add check for container running and log string presence to ensure correct setup and execution of Liquibase feat(Dockerfile.alpine): add volume mounts for classpath and changelog directories to allow for external configuration and customization

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -37,6 +37,21 @@ jobs:
         run: |
           docker run --name liquibase -d -v $(pwd)/.github/test:/liquibase/changelog liquibase/liquibase:${{ github.sha }} init start-h2
           docker logs liquibase
+          CONTAINER_NAME="liquibase"
+          LOG_STRING="jdbc:h2:tcp://localhost:9090/mem:dev"
+          # Check if the container is running
+          if docker inspect -f '{{.State.Running}}' "$CONTAINER_NAME" 2>/dev/null | grep -q "true"; then
+              # Get the logs and check if the desired string is present
+              if docker logs "$CONTAINER_NAME" 2>&1 | grep -q "$LOG_STRING"; then
+                  echo "The log contains the string: $LOG_STRING"
+              else
+                  echo "The log does not contain the string: $LOG_STRING"
+                  exit 1
+              fi
+          else
+              echo "Error: Container $CONTAINER_NAME is not running."
+              exit 2
+          fi
 
       - name: Run Liquibase version
         run: |
